[project]
name = "querynonomicon"
version = "0.3.0"
requires-python = ">=3.12"
dependencies = [
    "adbc-driver-sqlite",
    "click",
    "faker",
    "jupysql",
    "jupyter",
    "mccole",
    "pandas",
    "polars",
    "pyarrow",
    "pypika",
    "sqlmodel",
    "sqlparse"
]

[tool.mccole]
skips = ["CONTRIBUTING.md", "bin", "db", "extras", "templates"]

[tool.mccole.renames]
"README.md" = ""
"CODE_OF_CONDUCT.md" = "conduct"
"LICENSE.md" = "license"
"bibliography.md" = "bibliography"
"glossary.md" = "glossary"
